package String;

/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

https://leetcode.com/problems/find-the-difference/




/
 */
public class FindDifference {

    public static char findTheDifference(String s, String t) {

        int i =0;
        for(char c : s.toCharArray()){
            i ^= c;
        }

        for(char c : t.toCharArray()){
            i ^= c;
        }

        return (char)i;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde"));
    }
}
